### ISSUE TITLE
Sentry server errors when processing events from example code

### ISSUE THREAD

**Issue by davechallis** [SecurityInsanity/sentry-rs#16]
In sentry-rs 2.1.2 (Rust 1.24.0), using `logger-demo.rs` with my own Sentry credentials results in the Sentry server complaining about processing the event.

It shows up as an issue in the Sentry dashboard, but Sentry also reports the following:

<img width="933" alt="screen shot 2018-02-16 at 11 06 31" src="https://user-images.githubusercontent.com/208316/36304956-8362ba40-1309-11e8-95a6-0e22101a7ec8.png">

**Comment by SecurityInsanity** [comment]
Hey @davechallis ,

Thanks for bringing this up. I personally haven't seen this before, but I see where it can come from so I'll go ahead, and dig in here. I was planning on giving this crate a face-lift anyway to use hyper 0.11. So I can do this at the same time.

**Comment by davechallis** [comment]
@SecurityInsanity great, sounds good to me. Will be happy to help testing when the next version of the crate is out too.

**Comment by SecurityInsanity** [comment]
Sorry this is taking awhile! Luckily I've got some time slotted this weekend to solve this. So you should see some updates then.

**Comment by davechallis** [comment]
Sorry about the delay, got round to testing this now, all looks good to me, thanks for the fix.
